### ISSUE TITLE
Issue where and op player can't use staff chat

### ISSUE THREAD

**Issue by Xintilsword** [FranciscoDadone/StaffChatLite-Bungeecord#2]
Player has an op but it needed an a perms to use it 
![Screenshot_2022-07-19-18-07-18-22_572064f74bd5f9fa804b05334aa4f912](https://user-images.githubusercontent.com/108564217/179736599-fbf9459a-e453-4756-a66f-5f4a1df7d6cb.jpg)

**Comment by Zakaii12** [comment]
This issue also can be pass by using "#" but work sometimes

**Comment by FranciscoDadone** [comment]
Hello! I'm looking into it.

**Comment by Zakaii12** [comment]
Also how do i fix this 
![Screenshot_2022-07-25-20-18-47-75_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/108564217/180787194-aaacc955-5d9b-4b6d-88d6-9c1cd53d1540.jpg)

**Comment by Zakaii12** [comment]
Nope,i figured how to fix it by using luckperms bungee it can be fixed

**Comment by FranciscoDadone** [comment]
Yes It can be fixed with a permissions plugin. I researched and found nothing to detect a op player from bungee.
Soon I will be uploading an update for that error that you posted.

Thanks!
